const milestones = [
 {year:'1953',label:'Transistors',title:'Computers lose the tubes.',tag:'HARDWARE / SWITCHING',summary:'The Manchester transistor computer prototype demonstrated an alternative to vacuum-tube computing.',tech:'Transistors act as electronic switches. Their small size and low power needs helped reduce the space and heat associated with vacuum tubes. The first transistor had been demonstrated in 1947, before this era.',bottleneck:'Bulky, power-hungry circuitry → smaller solid-state components. Wiring many separate components remained a challenge.',impact:'More practical computers supported institutional data processing. Access still largely belonged to organizations with money and trained operators.'},
 {year:'1958–59',label:'Integrated circuits',title:'A circuit becomes a chip.',tag:'HARDWARE / INTEGRATION',summary:'Jack Kilby and Robert Noyce developed key approaches to the integrated circuit in 1958 and 1959.',tech:'Multiple electronic components could be formed on one semiconductor substrate. Silicon-based manufacturing enabled increasingly dense circuits with fewer external connections.',bottleneck:'Complex assembly of separate parts → integration on a chip. Manufacturing reliability and production cost still mattered.',impact:'Smaller electronics helped broaden computing applications. Semiconductor manufacturing and engineering became increasingly influential industries.'},
 {year:'1971',label:'Microprocessor',title:'The processor fits on silicon.',tag:'HARDWARE / COMPUTATION',summary:'Intel introduced the 4004, an early commercial single-chip microprocessor, for a calculator system.',tech:'The 4004 was a 4-bit CPU with approximately 2,300 transistors. It integrated central processing functions, while still requiring other chips for memory and input/output.',bottleneck:'A CPU assembled from many components → a programmable processor on one chip. Affordable complete systems were the next challenge.',impact:'Microprocessors supported embedded devices and helped make smaller computers possible, expanding opportunities for hardware and software development.'},
 {year:'1977',label:'Personal computers',title:'Computing comes closer to home.',tag:'HARDWARE / PERSONAL ACCESS',summary:'The Apple II, Commodore PET and TRS-80 marked an important wave of ready-made personal computers.',tech:'Microprocessors, RAM, keyboards and displays brought computing into smaller systems. Storage, memory and connectivity remained limited compared with modern machines.',bottleneck:'Institutional access → more individual ownership. Machines still needed useful software, skills and ways to exchange information.',impact:'People could learn programming and work with digital documents at home, school and work. Cost and access to training produced unequal opportunities.'},
 {year:'1989–91',label:'The early Web',title:'Documents gain a global address.',tag:'STANDARDS / HTTP + HTML',summary:'Tim Berners-Lee proposed the Web at CERN in 1989. A browser and server were working by late 1990, and the project reached the wider Internet in 1991.',tech:'URLs identify resources; HTTP carries requests and responses; HTML structures linked documents. These web technologies use the existing Internet, whose TCP/IP protocols connect networks.',bottleneck:'Information scattered across incompatible systems → linked documents using shared conventions. Ease of use and wider availability were still barriers.',impact:'Researchers could share and navigate information across computers. The same approach opened possibilities for wider publishing and learning.'},
 {year:'1993',label:'Wider adoption',title:'The Web opens its doors.',tag:'ACCESS / BROWSERS',summary:'CERN put its web software in the public domain on April 30. NCSA Mosaic helped popularize browsing with a graphical interface.',tech:'Browsers rendered linked text and images, making web navigation more approachable. Open web standards allowed different browsers and servers to communicate.',bottleneck:'Specialist tools and uncertainty about access → easier browsing and freely available web software. Finding trustworthy information became a growing challenge.',impact:'Publishing expanded beyond traditional gatekeepers. During the 1990s, websites supported new businesses and communities, while connectivity costs and digital literacy limited participation.'}
];
let selected=0;
const timeline=document.querySelector('#timeline');
milestones.forEach((m,i)=>{const button=document.createElement('button');button.innerHTML=`<b>${m.year}</b><small>${m.label}</small>`;button.addEventListener('click',()=>render(i));timeline.append(button)});
function render(index){selected=index;const m=milestones[index];document.querySelector('#detail').innerHTML=`<div><p class="year">${m.year}</p><span class="tag">${m.tag}</span><h3 class="detail-title">${m.title}</h3><p class="detail-summary">${m.summary}</p></div><div class="facts"><div><h3>Inside the technology</h3><p>${m.tech}</p></div><div><h3>The bottleneck → the breakthrough</h3><p>${m.bottleneck}</p></div><div><h3>People, power & labor</h3><p>${m.impact}</p></div></div>`;[...timeline.children].forEach((b,i)=>{if(i===index)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});document.querySelector('#progress-fill').style.width=`${(index+1)/milestones.length*100}%`;document.querySelector('#counter').textContent=`${index+1} / ${milestones.length}`;document.querySelector('#previous').disabled=index===0;document.querySelector('#next').disabled=index===milestones.length-1}
document.querySelector('#previous').addEventListener('click',()=>render(Math.max(0,selected-1)));
document.querySelector('#next').addEventListener('click',()=>render(Math.min(milestones.length-1,selected+1)));
render(0);
let requestStep=0;
const steps=[{text:'BROWSER → SERVER\nGET /index.html\n\nHTTP asks the server for a document.\nThis is a simplified exchange, not a live request.',button:'2. Receive the response →'},{text:'SERVER → BROWSER\n200 OK\nContent-Type: text/html\n\n<h1>Hello, world!</h1>\n<a href="next.html">Another page</a>',button:'3. Display the page →'},{text:'BROWSER\nHello, world!\nAnother page ↗\n\nThe browser interprets HTML.\nFollowing a link starts another request.',button:'Restart the exchange ↺'}];
document.querySelector('#request').addEventListener('click',()=>{const s=steps[requestStep];document.querySelector('#network').textContent=s.text;document.querySelector('#request').textContent=s.button;requestStep=(requestStep+1)%steps.length});
